### ISSUE TITLE
Failed to run robolectric tests for android project with Retrolambda

### ISSUE THREAD

**Issue by Yarikx** [evant/gradle-retrolambda#40] opened 2014-08-26 15:07 UTC
Got error java.lang.UnsupportedClassVersionError: com/example/app/R : Unsupported major.minor version 52.0

build config for test project:
```groovy
apply plugin: 'java'
apply plugin: 'retrolambda'

retrolambda {
    jdk System.getenv("JAVA8_HOME")
    oldJdk System.getenv("JAVA_HOME")
    javaVersion JavaVersion.VERSION_1_6
}

dependencies {
    def androidModule = project(':app')
    compile androidModule

    testCompile androidModule.android.applicationVariants.toList().first().javaCompile.classpath
    testCompile androidModule.android.applicationVariants.toList().first().javaCompile.outputs.files
    testCompile files(androidModule.plugins.findPlugin("com.android.application").getBootClasspath())

    testCompile 'junit:junit:4.+'
    testCompile 'org.robolectric:robolectric:2.2'
}

tasks.withType(Test) {
    scanForTestClasses = false
    include "**/*Should.class"
    include "**/*Test.class"
    include "**/*Tests.class"
}
```

**Comment by evant** [comment] 2015-03-31 00:43
I'm going to close this issue because a bunch of changes have been made to the respective projects since this was opened. Feel free to reopen if this is still an issue with you and you can reproduce it on the latests version(s).

**Closed by evant** 2015-03-31 00:43 UTC
